spring:
  datasource:
    url: jdbc:mysql://localhost:3306/addressbookdb?useSSL=false
    username: ${db_user}
    password: ${db_password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /address-book
  port: 8081