spring:
  datasource:
    url: jdbc:mysql://aws.amazon.com/address_book?useSSL=false
    username: ${db_url}
    password: ${db_password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /address-book
  port: 8081